=== CodeNarc/CodeNarc/src/main/resources/ruleset-schema.xsd
<?xml version="1.0"?>
  <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
      xmlns="http://codenarc.org/ruleset/1.0"
      targetNamespace="http://codenarc.org/ruleset/1.0"
      elementFormDefault="qualified"
      attributeFormDefault="unqualified"
    >

  <!-- Schema for a rule set for the CodeNarc tool. See http://codenarc.org. -->

  <xs:element name="ruleset">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="description" minOccurs="0" maxOccurs="1" />
        <xs:element ref="ruleset-ref" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="rule" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="rule-script" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="description" type="xs:string">
  </xs:element>

  <xs:element name="rule">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="property" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="class" type="xs:NMTOKEN" use="required" />
    </xs:complexType>
  </xs:element>

    <xs:element name="rule-script">
      <xs:complexType>
        <xs:sequence>
          <xs:element ref="property" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="path" type="xs:string" use="required" />
      </xs:complexType>
    </xs:element>

  <xs:element name="ruleset-ref">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="rule-config" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="include" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="exclude" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="path" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="rule-config">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="property" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="name" type="xs:NMTOKEN" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="property">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="value" minOccurs="0" maxOccurs="1" />
      </xs:sequence>
      <xs:attribute name="name" type="xs:NMTOKEN" use="required" />
      <xs:attribute name="value" type="xs:string" use="optional" />
      <xs:attribute name="description" type="xs:string" use="optional" />
    </xs:complexType>
  </xs:element>

  <xs:element name="value" type="xs:string">
  </xs:element>

  <xs:element name="include">
    <xs:complexType>
      <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="exclude">
    <xs:complexType>
      <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

</xs:schema>

=== CodeNarc/CodeNarc/src/main/resources/rulesets/junit.xml
<ruleset xmlns="http://codenarc.org/ruleset/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://codenarc.org/ruleset/1.0 http://codenarc.org/ruleset-schema.xsd"
        xsi:noNamespaceSchemaLocation="http://codenarc.org/ruleset-schema.xsd">

    <description>
        JUnit rule set.
        These rules implement standards and best practices related to JUnit tests.
    </description>

    <rule class='org.codenarc.rule.junit.ChainedTestRule'/>
    <rule class='org.codenarc.rule.junit.CoupledTestCaseRule'/>
    <rule class='org.codenarc.rule.junit.JUnitAssertAlwaysFailsRule'/>
    <rule class='org.codenarc.rule.junit.JUnitAssertAlwaysSucceedsRule'/>
    <rule class='org.codenarc.rule.junit.JUnitFailWithoutMessageRule'/>
    <rule class='org.codenarc.rule.junit.JUnitPublicNonTestMethodRule'/>
    <rule class='org.codenarc.rule.junit.JUnitPublicPropertyRule'/>
    <rule class='org.codenarc.rule.junit.JUnitLostTestRule'/>
    <rule class='org.codenarc.rule.junit.JUnitPublicFieldRule'/>
    <rule class='org.codenarc.rule.junit.JUnitSetUpCallsSuperRule'/>
    <rule class='org.codenarc.rule.junit.JUnitTearDownCallsSuperRule'/>
    <rule class='org.codenarc.rule.junit.JUnitStyleAssertionsRule'/>
    <rule class='org.codenarc.rule.junit.JUnitTestMethodWithoutAssertRule'/>
    <rule class='org.codenarc.rule.junit.JUnitUnnecessarySetUpRule'/>
    <rule class='org.codenarc.rule.junit.JUnitUnnecessaryTearDownRule'/>
    <rule class='org.codenarc.rule.junit.JUnitUnnecessaryThrowsExceptionRule'/>
    <rule class='org.codenarc.rule.junit.SpockIgnoreRestUsedRule'/>
    <rule class='org.codenarc.rule.junit.SpockMissingAssertRule'/>
    <rule class='org.codenarc.rule.junit.SpockUseVerifyEachRule'/>
    <rule class='org.codenarc.rule.junit.UnnecessaryFailRule'/>
    <rule class='org.codenarc.rule.junit.UseAssertTrueInsteadOfNegationRule'/>
    <rule class='org.codenarc.rule.junit.UseAssertFalseInsteadOfNegationRule'/>
    <rule class='org.codenarc.rule.junit.UseAssertEqualsInsteadOfAssertTrueRule'/>
    <rule class='org.codenarc.rule.junit.UseAssertTrueInsteadOfAssertEqualsRule'/>
    <rule class='org.codenarc.rule.junit.UseAssertNullInsteadOfAssertEqualsRule'/>
    <rule class='org.codenarc.rule.junit.UseAssertSameInsteadOfAssertTrueRule'/>
</ruleset>

=== CodeNarc/CodeNarc/src/main/resources/rulesets/logging.xml
<ruleset xmlns="http://codenarc.org/ruleset/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://codenarc.org/ruleset/1.0 http://codenarc.org/ruleset-schema.xsd"
        xsi:noNamespaceSchemaLocation="http://codenarc.org/ruleset-schema.xsd">

    <description>
        Logging rule set.
        These rules implement standards and best practices related to logging and output.
    </description>

    <rule class='org.codenarc.rule.logging.LoggerForDifferentClassRule'/>
    <rule class='org.codenarc.rule.logging.PrintlnRule'/>
    <rule class='org.codenarc.rule.logging.PrintStackTraceRule'/>
    <rule class='org.codenarc.rule.logging.SystemErrPrintRule'/>
    <rule class='org.codenarc.rule.logging.SystemOutPrintRule'/>

    <rule class='org.codenarc.rule.logging.LoggerWithWrongModifiersRule'/>
    <rule class='org.codenarc.rule.logging.MultipleLoggersRule'/>
    <rule class='org.codenarc.rule.logging.LoggingSwallowsStacktraceRule'/>
</ruleset>

=== CodeNarc/CodeNarc/src/main/resources/rulesets/unnecessary.xml
<ruleset xmlns="http://codenarc.org/ruleset/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://codenarc.org/ruleset/1.0 http://codenarc.org/ruleset-schema.xsd"
        xsi:noNamespaceSchemaLocation="http://codenarc.org/ruleset-schema.xsd">

    <description>
        Unnecessary rule set.
        These rules check for unnecessary code.
    </description>

    <rule class='org.codenarc.rule.unnecessary.AddEmptyStringRule'/>
    <rule class='org.codenarc.rule.unnecessary.ConsecutiveStringConcatenationRule'/>
    <rule class='org.codenarc.rule.unnecessary.ConsecutiveLiteralAppendsRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryBigDecimalInstantiationRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryBigIntegerInstantiationRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryBooleanExpressionRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryBooleanInstantiationRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryCallForLastElementRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryCallToSubstringRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryCastRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryCatchBlockRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryCollectCallRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryCollectionCallRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryConstructorRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryDefInFieldDeclarationRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryDefInMethodDeclarationRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryDefInVariableDeclarationRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryDotClassRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryDoubleInstantiationRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryElseStatementRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryFinalOnPrivateMethodRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryFloatInstantiationRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryGetterRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryGStringRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryIfStatementRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryInstanceOfCheckRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryInstantiationToGetClassRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryIntegerInstantiationRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryLongInstantiationRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryModOneRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryNullCheckBeforeInstanceOfRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryNullCheckRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryObjectReferencesRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryOverridingMethodRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryPackageReferenceRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryParenthesesForMethodCallWithClosureRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryPublicModifierRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryReturnKeywordRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessarySafeNavigationOperatorRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessarySelfAssignmentRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessarySemicolonRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessarySetterRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryStringInstantiationRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryTernaryExpressionRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryToStringRule'/>
    <rule class='org.codenarc.rule.unnecessary.UnnecessaryTransientModifierRule'/>
</ruleset>

=== CodeNarc/CodeNarc/src/main/resources/rulesets/groovyism.xml
<ruleset xmlns="http://codenarc.org/ruleset/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://codenarc.org/ruleset/1.0 http://codenarc.org/ruleset-schema.xsd"
        xsi:noNamespaceSchemaLocation="http://codenarc.org/ruleset-schema.xsd">

    <description>
        Groovy-ism rule set.
        These are rules for Groovy idiomatic usage, and Groovy-specific bad practices
    </description>

    <rule class='org.codenarc.rule.groovyism.AssignCollectionSortRule'/>
    <rule class='org.codenarc.rule.groovyism.AssignCollectionUniqueRule'/>
    <rule class='org.codenarc.rule.groovyism.ClosureAsLastMethodParameterRule'/>
    <rule class='org.codenarc.rule.groovyism.CollectAllIsDeprecatedRule'/>
    <rule class='org.codenarc.rule.groovyism.ConfusingMultipleReturnsRule'/>
    <rule class='org.codenarc.rule.groovyism.ExplicitArrayListInstantiationRule'/>
    <rule class='org.codenarc.rule.groovyism.ExplicitCallToPlusMethodRule'/>
    <rule class='org.codenarc.rule.groovyism.ExplicitCallToMinusMethodRule'/>
    <rule class='org.codenarc.rule.groovyism.ExplicitCallToMultiplyMethodRule'/>
    <rule class='org.codenarc.rule.groovyism.ExplicitCallToDivMethodRule'/>
    <rule class='org.codenarc.rule.groovyism.ExplicitCallToPowerMethodRule'/>
    <rule class='org.codenarc.rule.groovyism.ExplicitCallToModMethodRule'/>
    <rule class='org.codenarc.rule.groovyism.ExplicitCallToOrMethodRule'/>
    <rule class='org.codenarc.rule.groovyism.ExplicitCallToAndMethodRule'/>
    <rule class='org.codenarc.rule.groovyism.ExplicitCallToXorMethodRule'/>
    <rule class='org.codenarc.rule.groovyism.ExplicitCallToGetAtMethodRule'/>
    <rule class='org.codenarc.rule.groovyism.ExplicitCallToLeftShiftMethodRule'/>
    <rule class='org.codenarc.rule.groovyism.ExplicitCallToRightShiftMethodRule'/>
    <rule class='org.codenarc.rule.groovyism.ExplicitCallToCompareToMethodRule'/>
    <rule class='org.codenarc.rule.groovyism.ExplicitCallToEqualsMethodRule'/>
    <rule class='org.codenarc.rule.groovyism.ExplicitHashMapInstantiationRule'/>
    <rule class='org.codenarc.rule.groovyism.ExplicitLinkedHashMapInstantiationRule'/>
    <rule class='org.codenarc.rule.groovyism.ExplicitHashSetInstantiationRule'/>
    <rule class='org.codenarc.rule.groovyism.ExplicitLinkedListInstantiationRule'/>
    <rule class='org.codenarc.rule.groovyism.ExplicitStackInstantiationRule'/>
    <rule class='org.codenarc.rule.groovyism.ExplicitTreeSetInstantiationRule'/>
    <rule class='org.codenarc.rule.groovyism.GetterMethodCouldBePropertyRule'/>
    <rule class='org.codenarc.rule.groovyism.GroovyLangImmutableRule'/>
    <rule class='org.codenarc.rule.groovyism.GStringAsMapKeyRule'/>
    <rule class='org.codenarc.rule.groovyism.GStringExpressionWithinStringRule'/>
    <rule class='org.codenarc.rule.groovyism.UseCollectManyRule'/>
    <rule class='org.codenarc.rule.groovyism.UseCollectNestedRule'/>
    <rule class='org.codenarc.rule.groovyism.ExplicitCallToPutAtMethodRule'/>
</ruleset>

=== CodeNarc/CodeNarc/src/main/resources/rulesets/security.xml
<ruleset xmlns="http://codenarc.org/ruleset/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://codenarc.org/ruleset/1.0 http://codenarc.org/ruleset-schema.xsd"
        xsi:noNamespaceSchemaLocation="http://codenarc.org/ruleset-schema.xsd">

    <description>
        Security rule set.
        These rules find security problems within the source code.
    </description>

    <rule class='org.codenarc.rule.security.NonFinalSubclassOfSensitiveInterfaceRule'/>
    <rule class='org.codenarc.rule.security.InsecureRandomRule'/>
    <rule class='org.codenarc.rule.security.FileCreateTempFileRule'/>
    <rule class='org.codenarc.rule.security.SystemExitRule'/>
    <rule class='org.codenarc.rule.security.ObjectFinalizeRule'/>
    <rule class='org.codenarc.rule.security.JavaIoPackageAccessRule'/>
    <rule class='org.codenarc.rule.security.UnsafeArrayDeclarationRule'/>
    <rule class='org.codenarc.rule.security.PublicFinalizeMethodRule'/>
    <rule class='org.codenarc.rule.security.NonFinalPublicFieldRule'/>
    <rule class='org.codenarc.rule.security.UnsafeImplementationAsMapRule'/>
</ruleset>

=== CodeNarc/CodeNarc/src/main/resources/rulesets/design.xml
<ruleset xmlns="http://codenarc.org/ruleset/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://codenarc.org/ruleset/1.0 http://codenarc.org/ruleset-schema.xsd"
        xsi:noNamespaceSchemaLocation="http://codenarc.org/ruleset-schema.xsd">

    <description>
        Design rule set.
        These rules implement standards and best practices related to design issues.
    </description>

    <rule class='org.codenarc.rule.design.AbstractClassWithoutAbstractMethodRule'/>
    <rule class='org.codenarc.rule.design.AbstractClassWithPublicConstructorRule'/>
    <rule class='org.codenarc.rule.design.AssignmentToStaticFieldFromInstanceMethodRule'/>
    <rule class='org.codenarc.rule.design.BooleanMethodReturnsNullRule'/>
    <rule class='org.codenarc.rule.design.BuilderMethodWithSideEffectsRule'/>
    <rule class='org.codenarc.rule.design.CloneableWithoutCloneRule'/>
    <rule class='org.codenarc.rule.design.CloseWithoutCloseableRule'/>
    <rule class='org.codenarc.rule.design.CompareToWithoutComparableRule'/>
    <rule class='org.codenarc.rule.design.ConstantsOnlyInterfaceRule'/>
    <rule class='org.codenarc.rule.design.EmptyMethodInAbstractClassRule'/>
    <rule class='org.codenarc.rule.design.FinalClassWithProtectedMemberRule'/>
    <rule class='org.codenarc.rule.design.ImplementationAsTypeRule'/>
    <rule class='org.codenarc.rule.design.InstanceofRule'/>
    <rule class='org.codenarc.rule.design.LocaleSetDefaultRule'/>
    <rule class='org.codenarc.rule.design.NestedForLoopRule'/>
    <rule class='org.codenarc.rule.design.OptionalCollectionReturnTypeRule'/>
    <rule class='org.codenarc.rule.design.OptionalFieldRule'/>
    <rule class='org.codenarc.rule.design.OptionalMethodParameterRule'/>
    <rule class='org.codenarc.rule.design.PublicInstanceFieldRule'/>
    <rule class='org.codenarc.rule.design.PrivateFieldCouldBeFinalRule'/>
    <rule class='org.codenarc.rule.design.ReturnsNullInsteadOfEmptyArrayRule'/>
    <rule class='org.codenarc.rule.design.ReturnsNullInsteadOfEmptyCollectionRule'/>
    <rule class='org.codenarc.rule.design.SimpleDateFormatMissingLocaleRule'/>
    <rule class='org.codenarc.rule.design.StatelessSingletonRule'/>
    <rule class='org.codenarc.rule.design.ToStringReturnsNullRule'/>
</ruleset>

=== CodeNarc/CodeNarc/src/main/resources/rulesets/grails.xml
<ruleset xmlns="http://codenarc.org/ruleset/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://codenarc.org/ruleset/1.0 http://codenarc.org/ruleset-schema.xsd"
        xsi:noNamespaceSchemaLocation="http://codenarc.org/ruleset-schema.xsd">

    <description>
        Grails rule set.
        These rules implement standards and best practices related to the Grails framework (http://grails.org).
    </description>

    <rule class='org.codenarc.rule.grails.GrailsDomainHasEqualsRule'/>
    <rule class='org.codenarc.rule.grails.GrailsDomainHasToStringRule'/>
    <rule class='org.codenarc.rule.grails.GrailsDuplicateMappingRule'/>
    <rule class='org.codenarc.rule.grails.GrailsPublicControllerMethodRule'/>
    <rule class='org.codenarc.rule.grails.GrailsServletContextReferenceRule'/>
    <rule class='org.codenarc.rule.grails.GrailsSessionReferenceRule'/>
    <rule class='org.codenarc.rule.grails.GrailsStatelessServiceRule'/>
    <rule class='org.codenarc.rule.grails.GrailsDuplicateConstraintRule'/>
    <rule class='org.codenarc.rule.grails.GrailsDomainWithServiceReferenceRule'/>
    <rule class='org.codenarc.rule.grails.GrailsDomainReservedSqlKeywordNameRule'/>
    <rule class='org.codenarc.rule.grails.GrailsMassAssignmentRule'/>
</ruleset>

=== CodeNarc/CodeNarc/src/main/resources/rulesets/jenkins.xml
<ruleset xmlns="http://codenarc.org/ruleset/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://codenarc.org/ruleset/1.0 http://codenarc.org/ruleset-schema.xsd"
        xsi:noNamespaceSchemaLocation="http://codenarc.org/ruleset-schema.xsd">

    <description>
        Jenkins rule set.
        These rules implement best practices to avoid runtime errors
        from the CPS Interpreter in Jenkinsfiles and Jenkins libraries.
    </description>

    <rule class='org.codenarc.rule.jenkins.ParameterOrReturnTypeNotSerializableRule'/>
    <rule class='org.codenarc.rule.jenkins.ObjectOverrideOnlyNonCpsMethods'/>
    <rule class='org.codenarc.rule.jenkins.ForbiddenCallInCpsMethodRule'/>
    <rule class='org.codenarc.rule.jenkins.ExpressionInCpsMethodNotSerializableRule'/>
    <rule class='org.codenarc.rule.jenkins.CpsCallFromNonCpsMethodRule'/>
    <rule class='org.codenarc.rule.jenkins.ClosureInGStringRule'/>
    <rule class='org.codenarc.rule.jenkins.ClassNotSerializableRule'/>

</ruleset>
