=== CodeNarc/CodeNarc/src/main/resources/ruleset-schema.xsd
<?xml version="1.0"?>
  <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
      xmlns="http://codenarc.org/ruleset/1.0"
      targetNamespace="http://codenarc.org/ruleset/1.0"
      elementFormDefault="qualified"
      attributeFormDefault="unqualified"
    >

  <!-- Schema for a rule set for the CodeNarc tool. See http://codenarc.org. -->

  <xs:element name="ruleset">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="description" minOccurs="0" maxOccurs="1" />
        <xs:element ref="ruleset-ref" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="rule" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="rule-script" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="description" type="xs:string">
  </xs:element>

  <xs:element name="rule">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="property" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="class" type="xs:NMTOKEN" use="required" />
    </xs:complexType>
  </xs:element>

    <xs:element name="rule-script">
      <xs:complexType>
        <xs:sequence>
          <xs:element ref="property" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="path" type="xs:string" use="required" />
      </xs:complexType>
    </xs:element>

  <xs:element name="ruleset-ref">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="rule-config" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="include" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="exclude" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="path" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="rule-config">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="property" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="name" type="xs:NMTOKEN" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="property">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="value" minOccurs="0" maxOccurs="1" />
      </xs:sequence>
      <xs:attribute name="name" type="xs:NMTOKEN" use="required" />
      <xs:attribute name="value" type="xs:string" use="optional" />
      <xs:attribute name="description" type="xs:string" use="optional" />
    </xs:complexType>
  </xs:element>

  <xs:element name="value" type="xs:string">
  </xs:element>

  <xs:element name="include">
    <xs:complexType>
      <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="exclude">
    <xs:complexType>
      <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

</xs:schema>

=== CodeNarc/CodeNarc/src/main/resources/rulesets/convention.xml
<ruleset xmlns="http://codenarc.org/ruleset/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://codenarc.org/ruleset/1.0 http://codenarc.org/ruleset-schema.xsd"
        xsi:noNamespaceSchemaLocation="http://codenarc.org/ruleset-schema.xsd">

    <description>
        Convention rule set.
        These are rules for coding conventions; not necessarily errors.
    </description>

    <rule class='org.codenarc.rule.convention.CompileStaticRule'/>
    <rule class='org.codenarc.rule.convention.ConfusingTernaryRule'/>
    <rule class='org.codenarc.rule.convention.CouldBeElvisRule'/>
    <rule class='org.codenarc.rule.convention.CouldBeSwitchStatementRule'/>
    <rule class='org.codenarc.rule.convention.HashtableIsObsoleteRule'/>
    <rule class='org.codenarc.rule.convention.FieldTypeRequiredRule'/>
    <rule class='org.codenarc.rule.convention.IfStatementCouldBeTernaryRule'/>
    <rule class='org.codenarc.rule.convention.ImplicitClosureParameterRule'/>
    <rule class='org.codenarc.rule.convention.ImplicitReturnStatementRule'/>
    <rule class='org.codenarc.rule.convention.InvertedIfElseRule'/>
    <rule class='org.codenarc.rule.convention.InvertedConditionRule'/>
    <rule class='org.codenarc.rule.convention.LongLiteralWithLowerCaseLRule'/>
    <rule class='org.codenarc.rule.convention.MethodParameterTypeRequired'/>
    <rule class='org.codenarc.rule.convention.MethodReturnTypeRequiredRule'/>
    <rule class='org.codenarc.rule.convention.NoDefRule'/>
    <rule class='org.codenarc.rule.convention.NoDoubleRule'/>
    <rule class='org.codenarc.rule.convention.NoFloatRule'/>
    <rule class='org.codenarc.rule.convention.NoJavaUtilDateRule'/>
    <rule class='org.codenarc.rule.convention.NoTabCharacterRule'/>
    <rule class='org.codenarc.rule.convention.ParameterReassignmentRule'/>
    <rule class='org.codenarc.rule.convention.PublicMethodsBeforeNonPublicMethodsRule'/>
    <rule class='org.codenarc.rule.convention.StaticFieldsBeforeInstanceFieldsRule'/>
    <rule class='org.codenarc.rule.convention.StaticMethodsBeforeInstanceMethodsRule'/>
    <rule class='org.codenarc.rule.convention.TernaryCouldBeElvisRule'/>
    <rule class='org.codenarc.rule.convention.TrailingCommaRule'/>
    <rule class='org.codenarc.rule.convention.VariableTypeRequiredRule'/>
    <rule class='org.codenarc.rule.convention.VectorIsObsoleteRule'/>
</ruleset>

=== CodeNarc/CodeNarc/src/main/resources/rulesets/concurrency.xml
<ruleset xmlns="http://codenarc.org/ruleset/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://codenarc.org/ruleset/1.0 http://codenarc.org/ruleset-schema.xsd"
        xsi:noNamespaceSchemaLocation="http://codenarc.org/ruleset-schema.xsd">

    <description>
        Concurrency rule set.
        These rules check for unsafe or unrecommended practices related to concurrency.
    </description>

    <rule class='org.codenarc.rule.concurrency.BusyWaitRule'/>
    <rule class='org.codenarc.rule.concurrency.DoubleCheckedLockingRule'/>
    <rule class='org.codenarc.rule.concurrency.InconsistentPropertyLockingRule'/>
    <rule class='org.codenarc.rule.concurrency.InconsistentPropertySynchronizationRule'/>
    <rule class='org.codenarc.rule.concurrency.NestedSynchronizationRule'/>
    <rule class='org.codenarc.rule.concurrency.StaticCalendarFieldRule'/>
    <rule class='org.codenarc.rule.concurrency.StaticConnectionRule'/>
    <rule class='org.codenarc.rule.concurrency.StaticDateFormatFieldRule'/>
    <rule class='org.codenarc.rule.concurrency.StaticMatcherFieldRule'/>
    <rule class='org.codenarc.rule.concurrency.StaticSimpleDateFormatFieldRule'/>
    <rule class='org.codenarc.rule.concurrency.SynchronizedOnBoxedPrimitiveRule'/>
    <rule class='org.codenarc.rule.concurrency.SynchronizedMethodRule'/>
    <rule class='org.codenarc.rule.concurrency.SynchronizedOnThisRule'/>
    <rule class='org.codenarc.rule.concurrency.SynchronizedOnGetClassRule'/>
    <rule class='org.codenarc.rule.concurrency.SynchronizedOnReentrantLockRule'/>
    <rule class='org.codenarc.rule.concurrency.SynchronizedOnStringRule'/>
    <rule class='org.codenarc.rule.concurrency.SynchronizedReadObjectMethodRule'/>
    <rule class='org.codenarc.rule.concurrency.SystemRunFinalizersOnExitRule'/>
    <rule class='org.codenarc.rule.concurrency.ThisReferenceEscapesConstructorRule'/>
    <rule class='org.codenarc.rule.concurrency.ThreadGroupRule'/>
    <rule class='org.codenarc.rule.concurrency.ThreadLocalNotStaticFinalRule'/>
    <rule class='org.codenarc.rule.concurrency.ThreadYieldRule'/>
    <rule class='org.codenarc.rule.concurrency.UseOfNotifyMethodRule'/>
    <rule class='org.codenarc.rule.concurrency.VolatileArrayFieldRule'/>
    <rule class='org.codenarc.rule.concurrency.VolatileLongOrDoubleFieldRule'/>
    <rule class='org.codenarc.rule.concurrency.WaitOutsideOfWhileLoopRule'/>
</ruleset>

=== CodeNarc/CodeNarc/src/main/resources/rulesets/exceptions.xml
<ruleset xmlns="http://codenarc.org/ruleset/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://codenarc.org/ruleset/1.0 http://codenarc.org/ruleset-schema.xsd"
        xsi:noNamespaceSchemaLocation="http://codenarc.org/ruleset-schema.xsd">

    <description>
        Exceptions rule set.
        These rules implement standards and best practices related to catching and throwing of exceptions.
    </description>

    <rule class='org.codenarc.rule.exceptions.CatchArrayIndexOutOfBoundsExceptionRule'/>
    <rule class='org.codenarc.rule.exceptions.CatchErrorRule'/>
    <rule class='org.codenarc.rule.exceptions.CatchExceptionRule'/>
    <rule class='org.codenarc.rule.exceptions.CatchIllegalMonitorStateExceptionRule'/>
    <rule class='org.codenarc.rule.exceptions.CatchIndexOutOfBoundsExceptionRule'/>
    <rule class='org.codenarc.rule.exceptions.CatchNullPointerExceptionRule'/>
    <rule class='org.codenarc.rule.exceptions.CatchRuntimeExceptionRule'/>
    <rule class='org.codenarc.rule.exceptions.CatchThrowableRule'/>
    <rule class='org.codenarc.rule.exceptions.ConfusingClassNamedExceptionRule'/>
    <rule class='org.codenarc.rule.exceptions.ExceptionExtendsErrorRule'/>
    <rule class='org.codenarc.rule.exceptions.ExceptionExtendsThrowableRule'/>
    <rule class='org.codenarc.rule.exceptions.ExceptionNotThrownRule'/>
    <rule class='org.codenarc.rule.exceptions.MissingNewInThrowStatementRule'/>
    <rule class='org.codenarc.rule.exceptions.ReturnNullFromCatchBlockRule'/>
    <rule class='org.codenarc.rule.exceptions.SwallowThreadDeathRule'/>
    <rule class='org.codenarc.rule.exceptions.ThrowErrorRule'/>
    <rule class='org.codenarc.rule.exceptions.ThrowExceptionRule'/>
    <rule class='org.codenarc.rule.exceptions.ThrowNullPointerExceptionRule'/>
    <rule class='org.codenarc.rule.exceptions.ThrowRuntimeExceptionRule'/>
    <rule class='org.codenarc.rule.exceptions.ThrowThrowableRule'/>
</ruleset>
