=== CodeNarc/CodeNarc/src/main/resources/ruleset-schema.xsd
<?xml version="1.0"?>
  <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
      xmlns="http://codenarc.org/ruleset/1.0"
      targetNamespace="http://codenarc.org/ruleset/1.0"
      elementFormDefault="qualified"
      attributeFormDefault="unqualified"
    >

  <!-- Schema for a rule set for the CodeNarc tool. See http://codenarc.org. -->

  <xs:element name="ruleset">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="description" minOccurs="0" maxOccurs="1" />
        <xs:element ref="ruleset-ref" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="rule" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="rule-script" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="description" type="xs:string">
  </xs:element>

  <xs:element name="rule">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="property" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="class" type="xs:NMTOKEN" use="required" />
    </xs:complexType>
  </xs:element>

    <xs:element name="rule-script">
      <xs:complexType>
        <xs:sequence>
          <xs:element ref="property" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="path" type="xs:string" use="required" />
      </xs:complexType>
    </xs:element>

  <xs:element name="ruleset-ref">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="rule-config" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="include" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="exclude" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="path" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="rule-config">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="property" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="name" type="xs:NMTOKEN" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="property">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="value" minOccurs="0" maxOccurs="1" />
      </xs:sequence>
      <xs:attribute name="name" type="xs:NMTOKEN" use="required" />
      <xs:attribute name="value" type="xs:string" use="optional" />
      <xs:attribute name="description" type="xs:string" use="optional" />
    </xs:complexType>
  </xs:element>

  <xs:element name="value" type="xs:string">
  </xs:element>

  <xs:element name="include">
    <xs:complexType>
      <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="exclude">
    <xs:complexType>
      <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

</xs:schema>

=== CodeNarc/CodeNarc/samples/rulesets/SampleRuleSet2.xml
<ruleset xmlns="http://codenarc.org/ruleset/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://codenarc.org/ruleset/1.0 http://codenarc.org/ruleset-schema.xsd"
        xsi:noNamespaceSchemaLocation="http://codenarc.org/ruleset-schema.xsd">

    <description>Sample rule set #2</description>

    <ruleset-ref path='rulesets/imports.xml'/>

    <ruleset-ref path='rulesets/basic.xml'>
        <exclude name='StringInstantiation'/>
    </ruleset-ref>

    <ruleset-ref path='rulesets/size.xml'>
        <rule-config name='ClassSize'>
            <property name='maxLines' value='500'/>
        </rule-config>
    </ruleset-ref>

    <rule class='org.codenarc.rule.generic.IllegalRegexRule'>
        <property name="name" value="AuthorTagNotAllowed"/>
        <property name='regex' value='\@author'/>
    </rule>

    <rule class='org.codenarc.rule.naming.VariableNameRule'>
        <property name="finalRegex" value="F_[A-Z0-9]*"/>
        <property name='priority' value='1'/>
    </rule>

</ruleset>

=== CodeNarc/CodeNarc/samples/rulesets/SampleRuleSet.xml
<ruleset xmlns="http://codenarc.org/ruleset/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://codenarc.org/ruleset/1.0 http://codenarc.org/ruleset-schema.xsd"
        xsi:noNamespaceSchemaLocation="http://codenarc.org/ruleset-schema.xsd">

    <description>Sample rule set</description>

    <ruleset-ref path='rulesets/imports.xml'>
        <rule-config name='DuplicateImport'>
            <property name='priority' value='1'/>
        </rule-config>
    </ruleset-ref>

    <ruleset-ref path='rulesets/basic.xml'>
        <exclude name='StringInstantiation'/>
    </ruleset-ref>

    <rule class='org.codenarc.rule.exceptions.CatchThrowableRule'>
        <property name='priority' value='1'/>
    </rule>

</ruleset>

=== CodeNarc/CodeNarc/src/main/resources/rulesets/size.xml
<ruleset xmlns="http://codenarc.org/ruleset/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://codenarc.org/ruleset/1.0 http://codenarc.org/ruleset-schema.xsd"
        xsi:noNamespaceSchemaLocation="http://codenarc.org/ruleset-schema.xsd">

    <description>
        Size and complexity rule set.
        These rules check against thresholds for code size and complexity.
    </description>

    <rule class='org.codenarc.rule.size.AbcMetricRule'/>
    <rule class='org.codenarc.rule.size.ClassSizeRule'/>
    <rule class='org.codenarc.rule.size.CrapMetricRule'/>
    <rule class='org.codenarc.rule.size.CyclomaticComplexityRule'/>
    <rule class='org.codenarc.rule.size.MethodCountRule'/>
    <rule class='org.codenarc.rule.size.MethodSizeRule'/>
    <rule class='org.codenarc.rule.size.NestedBlockDepthRule'/>
    <rule class='org.codenarc.rule.size.ParameterCountRule'/>
</ruleset>

=== CodeNarc/CodeNarc/src/main/resources/rulesets/imports.xml
<ruleset xmlns="http://codenarc.org/ruleset/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://codenarc.org/ruleset/1.0 http://codenarc.org/ruleset-schema.xsd"
        xsi:noNamespaceSchemaLocation="http://codenarc.org/ruleset-schema.xsd">

    <description>
        Imports rule set.
        These rules implement standards and best practices related to import statements.
    </description>

    <rule class='org.codenarc.rule.imports.DuplicateImportRule'/>
    <rule class='org.codenarc.rule.imports.ImportFromSamePackageRule'/>
    <rule class='org.codenarc.rule.imports.UnnecessaryGroovyImportRule'/>
    <rule class='org.codenarc.rule.imports.UnusedImportRule'/>

    <rule class='org.codenarc.rule.imports.ImportFromSunPackagesRule'/>
    <rule class='org.codenarc.rule.imports.MisorderedStaticImportsRule'/>
    <rule class='org.codenarc.rule.imports.NoWildcardImportsRule'/>
</ruleset>

=== CodeNarc/CodeNarc/src/main/resources/rulesets/naming.xml
<ruleset xmlns="http://codenarc.org/ruleset/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://codenarc.org/ruleset/1.0 http://codenarc.org/ruleset-schema.xsd"
        xsi:noNamespaceSchemaLocation="http://codenarc.org/ruleset-schema.xsd">

    <description>
        Naming rule set.
        These rules validate names within the source code.
    </description>

    <rule class='org.codenarc.rule.naming.AbstractClassNameRule'/>
    <rule class='org.codenarc.rule.naming.ClassNameRule'/>
    <rule class='org.codenarc.rule.naming.ClassNameSameAsFilenameRule'/>
    <rule class='org.codenarc.rule.naming.ConfusingMethodNameRule'/>
    <rule class='org.codenarc.rule.naming.FieldNameRule'/>
    <rule class='org.codenarc.rule.naming.InterfaceNameRule'/>
    <rule class='org.codenarc.rule.naming.MethodNameRule'/>
    <rule class='org.codenarc.rule.naming.ObjectOverrideMisspelledMethodNameRule'/>
    <rule class='org.codenarc.rule.naming.PackageNameRule'/>
    <rule class='org.codenarc.rule.naming.PackageNameMatchesFilePathRule'/>
    <rule class='org.codenarc.rule.naming.ParameterNameRule'/>
    <rule class='org.codenarc.rule.naming.PropertyNameRule'/>
    <rule class='org.codenarc.rule.naming.VariableNameRule'/>
    <rule class='org.codenarc.rule.naming.FactoryMethodNameRule'/>
</ruleset>

=== CodeNarc/CodeNarc/src/main/resources/rulesets/formatting.xml
<ruleset xmlns="http://codenarc.org/ruleset/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://codenarc.org/ruleset/1.0 http://codenarc.org/ruleset-schema.xsd"
        xsi:noNamespaceSchemaLocation="http://codenarc.org/ruleset-schema.xsd">

    <description>
        Formatting rule set.
        These rules find formatting problems within the source code.
    </description>

    <rule class='org.codenarc.rule.formatting.BlankLineBeforePackageRule'/>
    <rule class='org.codenarc.rule.formatting.BlockEndsWithBlankLineRule'/>
    <rule class='org.codenarc.rule.formatting.BlockStartsWithBlankLineRule'/>
    <rule class='org.codenarc.rule.formatting.BracesForClassRule'/>
    <rule class='org.codenarc.rule.formatting.BracesForForLoopRule'/>
    <rule class='org.codenarc.rule.formatting.BracesForIfElseRule'/>
    <rule class='org.codenarc.rule.formatting.BracesForMethodRule'/>
    <rule class='org.codenarc.rule.formatting.BracesForTryCatchFinallyRule'/>
    <rule class='org.codenarc.rule.formatting.ClosureStatementOnOpeningLineOfMultipleLineClosureRule'/>
    <rule class='org.codenarc.rule.formatting.ConsecutiveBlankLinesRule'/>
    <rule class='org.codenarc.rule.formatting.FileEndsWithoutNewlineRule'/>
    <rule class='org.codenarc.rule.formatting.IndentationRule'/>
    <rule class='org.codenarc.rule.formatting.LineLengthRule'/>
    <rule class='org.codenarc.rule.formatting.MissingBlankLineAfterImportsRule'/>
    <rule class='org.codenarc.rule.formatting.MissingBlankLineAfterPackageRule'/>
    <rule class='org.codenarc.rule.formatting.SpaceAfterCatchRule'/>
    <rule class='org.codenarc.rule.formatting.SpaceAfterClosingBraceRule'/>
    <rule class='org.codenarc.rule.formatting.SpaceAfterCommaRule'/>
    <rule class='org.codenarc.rule.formatting.SpaceAfterForRule'/>
    <rule class='org.codenarc.rule.formatting.SpaceAfterIfRule'/>
    <rule class='org.codenarc.rule.formatting.SpaceAfterOpeningBraceRule'/>
    <rule class='org.codenarc.rule.formatting.SpaceAfterSemicolonRule'/>
    <rule class='org.codenarc.rule.formatting.SpaceAfterSwitchRule'/>
    <rule class='org.codenarc.rule.formatting.SpaceAfterWhileRule'/>
    <rule class='org.codenarc.rule.formatting.SpaceAroundClosureArrowRule'/>
    <rule class='org.codenarc.rule.formatting.SpaceAroundMapEntryColonRule'/>
    <rule class='org.codenarc.rule.formatting.SpaceAroundOperatorRule'/>
    <rule class='org.codenarc.rule.formatting.SpaceBeforeClosingBraceRule'/>
    <rule class='org.codenarc.rule.formatting.SpaceBeforeOpeningBraceRule'/>
    <rule class='org.codenarc.rule.formatting.TrailingWhitespaceRule'/>
    <rule class='org.codenarc.rule.formatting.ClassEndsWithBlankLineRule'/>
    <rule class='org.codenarc.rule.formatting.ClassStartsWithBlankLineRule'/>
</ruleset>

=== CodeNarc/CodeNarc/src/main/resources/rulesets/basic.xml
<ruleset xmlns="http://codenarc.org/ruleset/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://codenarc.org/ruleset/1.0 http://codenarc.org/ruleset-schema.xsd"
        xsi:noNamespaceSchemaLocation="http://codenarc.org/ruleset-schema.xsd">

    <description>
        Basic rule set.
        These rules are intended to be broadly (if not universally) applicable.
    </description>

    <rule class='org.codenarc.rule.basic.AssertWithinFinallyBlockRule'/>
    <rule class='org.codenarc.rule.basic.AssignmentInConditionalRule'/>
    <rule class='org.codenarc.rule.basic.BigDecimalInstantiationRule'/>
    <rule class='org.codenarc.rule.basic.BitwiseOperatorInConditionalRule'/>
    <rule class='org.codenarc.rule.basic.BooleanGetBooleanRule'/>
    <rule class='org.codenarc.rule.basic.BrokenNullCheckRule'/>
    <rule class='org.codenarc.rule.basic.BrokenOddnessCheckRule'/>
    <rule class='org.codenarc.rule.basic.ClassForNameRule'/>
    <rule class='org.codenarc.rule.basic.ComparisonOfTwoConstantsRule'/>
    <rule class='org.codenarc.rule.basic.ComparisonWithSelfRule'/>
    <rule class='org.codenarc.rule.basic.ConstantAssertExpressionRule'/>
    <rule class='org.codenarc.rule.basic.ConstantTernaryExpressionRule'/>
    <rule class='org.codenarc.rule.basic.ConstantIfExpressionRule'/>
    <rule class='org.codenarc.rule.basic.DeadCodeRule'/>
    <rule class='org.codenarc.rule.basic.DoubleNegativeRule'/>
    <rule class='org.codenarc.rule.basic.DuplicateCaseStatementRule'/>
    <rule class='org.codenarc.rule.basic.DuplicateMapKeyRule'/>
    <rule class='org.codenarc.rule.basic.DuplicateSetValueRule'/>
    <rule class='org.codenarc.rule.basic.EmptyCatchBlockRule'/>
    <rule class='org.codenarc.rule.basic.EmptyClassRule'/>
    <rule class='org.codenarc.rule.basic.EmptyElseBlockRule'/>
    <rule class='org.codenarc.rule.basic.EmptyFinallyBlockRule'/>
    <rule class='org.codenarc.rule.basic.EmptyForStatementRule'/>
    <rule class='org.codenarc.rule.basic.EmptyIfStatementRule'/>
    <rule class='org.codenarc.rule.basic.EmptySwitchStatementRule'/>
    <rule class='org.codenarc.rule.basic.EmptySynchronizedStatementRule'/>
    <rule class='org.codenarc.rule.basic.EmptyStaticInitializerRule'/>
    <rule class='org.codenarc.rule.basic.EmptyTryBlockRule'/>
    <rule class='org.codenarc.rule.basic.EmptyWhileStatementRule'/>
    <rule class='org.codenarc.rule.basic.EmptyInstanceInitializerRule'/>
    <rule class='org.codenarc.rule.basic.EmptyMethodRule'/>
    <rule class='org.codenarc.rule.basic.EqualsAndHashCodeRule'/>
    <rule class='org.codenarc.rule.basic.EqualsOverloadedRule'/>
    <rule class='org.codenarc.rule.basic.ExplicitGarbageCollectionRule'/>
    <rule class='org.codenarc.rule.basic.ForLoopShouldBeWhileLoopRule'/>
    <rule class='org.codenarc.rule.basic.HardCodedWindowsFileSeparatorRule'/>
    <rule class='org.codenarc.rule.basic.HardCodedWindowsRootDirectoryRule'/>
    <rule class='org.codenarc.rule.basic.IntegerGetIntegerRule'/>
    <rule class='org.codenarc.rule.basic.RandomDoubleCoercedToZeroRule'/>
    <rule class='org.codenarc.rule.basic.RemoveAllOnSelfRule'/>
    <rule class='org.codenarc.rule.basic.ReturnFromFinallyBlockRule'/>
    <rule class='org.codenarc.rule.basic.ThrowExceptionFromFinallyBlockRule'/>
</ruleset>

=== CodeNarc/CodeNarc/src/main/resources/rulesets/generic.xml
<ruleset xmlns="http://codenarc.org/ruleset/1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://codenarc.org/ruleset/1.0 http://codenarc.org/ruleset-schema.xsd"
        xsi:noNamespaceSchemaLocation="http://codenarc.org/ruleset-schema.xsd">

    <description>
        Generic rule set.
        These rules are generic, and are intended to be customized.
    </description>

    <rule class='org.codenarc.rule.generic.IllegalClassMemberRule'/>
    <rule class='org.codenarc.rule.generic.IllegalClassReferenceRule'/>
    <rule class='org.codenarc.rule.generic.IllegalPackageReferenceRule'/>
    <rule class='org.codenarc.rule.generic.IllegalRegexRule'/>
    <rule class='org.codenarc.rule.generic.IllegalStringRule'/>
    <rule class='org.codenarc.rule.generic.IllegalSubclassRule'/>
    <rule class='org.codenarc.rule.generic.RequiredRegexRule'/>
    <rule class='org.codenarc.rule.generic.RequiredStringRule'/>
    <rule class='org.codenarc.rule.generic.StatelessClassRule'/>
</ruleset>
